### ISSUE TITLE
ExampleTest fails on laravel 5.5 dusk

### ISSUE THREAD

**Issue by designbyjr** [appstract/laravel-dusk-safari#2]
There was 1 error:

1) Tests\Browser\ExampleTest::testBasicExample
TypeError: Argument 1 passed to Facebook\WebDriver\Remote\DesiredCapabilities::__construct() must be of the type array, null given, called in /Users/jamie/Documents/work/demotwo/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php on line 127

/Users/jamie/Documents/work/demotwo/vendor/facebook/webdriver/lib/Remote/DesiredCapabilities.php:33
/Users/jamie/Documents/work/demotwo/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:127
/Users/jamie/Documents/work/demotwo/tests/DuskTestCase.php:47
/Users/jamie/Documents/work/demotwo/vendor/laravel/dusk/src/TestCase.php:210
/Users/jamie/Documents/work/demotwo/vendor/laravel/framework/src/Illuminate/Support/helpers.php:762
/Users/jamie/Documents/work/demotwo/vendor/laravel/dusk/src/TestCase.php:211
/Users/jamie/Documents/work/demotwo/vendor/laravel/dusk/src/TestCase.php:117
/Users/jamie/Documents/work/demotwo/vendor/laravel/dusk/src/TestCase.php:89
/Users/jamie/Documents/work/demotwo/tests/Browser/ExampleTest.php:21

**Comment by ovanschie** [comment]
Just tested on a clean 5.5 install, and it works fine.

Make sure your driver method looks like this:

    protected function driver()
    {
        return RemoteWebDriver::create(
            'http://localhost:9515', DesiredCapabilities::safari()
        );
    }

**Comment by nikkolai14** [comment]
This reply is quite late but I will instead post it here who ever has this problem since it is not clearly written in the laravel doc.

1) You will need to download ChromeDriver in this link [here](https://sites.google.com/a/chromium.org/chromedriver/home)
2) Make sure of the version that is the same in your chrome browser,
3) Run the Chromedriver standalone in terminal
4) make sure of the port is the same from the ChromeDriver terminal to the DuskTestCase class driver method

**Comment by ram2228** [comment]
The issue is got fixed .
solution worked for me (windows) :  run the chromedriver-win.exe in vendor\laravel\dusk\bin
and see the port number from command promt
<img width="848" alt="image" src="https://github.com/user-attachments/assets/4e558444-1f33-4647-b925-531ef912cd68">

match the port number in tests/DuskTestCase.php
 protected function driver(): RemoteWebDriver
    {
        $capabilities = DesiredCapabilities::chrome();
        //dd($capabilities);
        return RemoteWebDriver::create(
            'http://127.0.0.1:54064', $capabilities
        );
    }

then it got worked for me.
ping me if any further issues
